Syscall = {
    "i386": [
        ['restart_syscall'],
        ['exit', 'error_code'],
        ['fork', 'pt_regs'],
        ['read', 'fd', 'buf', 'count'],
        ['write', 'fd', 'buf', 'count'],
        ['open', 'filename', 'flags', 'mode'],
        ['close', 'fd'],
        ['waitpid', 'pid', 'stat_addr', 'options'],
        ['creat', 'pathname', 'mode'],
        ['link', 'oldname', 'newname'],
        ['unlink', 'pathname'],
        ['execve', '__user', '__user', '__user', 'pt_regs'],
        ['chdir', 'filename'],
        ['time', 'tloc'],
        ['mknod', 'filename', 'mode', 'dev'],
        ['chmod', 'filename', 'mode'],
        ['lchown16', 'filename', 'user', 'group'],
        ['not implemented'],
        ['stat', 'filename', 'statbuf'],
        ['lseek', 'fd', 'offset', 'origin'],
        ['getpid'],
        ['mount', 'dev_name', 'dir_name', 'type', 'flags', 'data'],
        ['oldumount', 'name'],
        ['setuid16', 'uid'],
        ['getuid16'],
        ['stime', 'tptr'],
        ['ptrace', 'request', 'pid', 'addr', 'data'],
        ['alarm', 'seconds'],
        ['fstat', 'fd', 'statbuf'],
        ['pause'],
        ['utime', 'filename', 'times'],
        ['not implemented'],
        ['not implemented'],
        ['access', 'filename', 'mode'],
        ['nice', 'increment'],
        ['not implemented'],
        ['sync'],
        ['kill', 'pid', 'sig'],
        ['rename', 'oldname', 'newname'],
        ['mkdir', 'pathname', 'mode'],
        ['rmdir', 'pathname'],
        ['dup', 'fildes'],
        ['pipe', 'fildes'],
        ['times', 'tbuf'],
        ['not implemented'],
        ['brk', 'brk'],
        ['setgid16', 'gid'],
        ['getgid16'],
        ['signal', 'sig', 'handler'],
        ['geteuid16'],
        ['getegid16'],
        ['acct', 'name'],
        ['umount', 'name', 'flags'],
        ['not implemented'],
        ['ioctl', 'fd', 'cmd', 'arg'],
        ['fcntl', 'fd', 'cmd', 'arg'],
        ['not implemented'],
        ['setpgid', 'pid', 'pgid'],
        ['not implemented'],
        ['olduname', '__user'],
        ['umask', 'mask'],
        ['chroot', 'filename'],
        ['ustat', 'dev', 'ubuf'],
        ['dup2', 'oldfd', 'newfd'],
        ['getppid'],
        ['getpgrp'],
        ['setsid'],
        ['sigaction', 'sig', 'act', 'oact'],
        ['sgetmask'],
        ['ssetmask', 'newmask'],
        ['setreuid16', 'ruid', 'euid'],
        ['setregid16', 'rgid', 'egid'],
        ['sigsuspend', 'history0', 'history1', 'mask'],
        ['sigpending', 'set'],
        ['sethostname', 'name', 'len'],
        ['setrlimit', 'resource', 'rlim'],
        ['old_getrlimit', 'resource', 'rlim'],
        ['getrusage', 'who', 'ru'],
        ['gettimeofday', 'tv', 'tz'],
        ['settimeofday', 'tv', 'tz'],
        ['getgroups16', 'gidsetsize', 'grouplist'],
        ['setgroups16', 'gidsetsize', 'grouplist'],
        ['old_select', 'arg'],
        ['symlink', 'old', 'new'],
        ['lstat', 'filename', 'statbuf'],
        ['readlink', 'path', 'buf', 'bufsiz'],
        ['uselib', 'library'],
        ['swapon', 'specialfile', 'swap_flags'],
        ['reboot', 'magic1', 'magic2', 'cmd', 'arg'],
        ['old_readdir', 'fd', 'dirent', 'count'],
        ['old_mmap', 'arg'],
        ['munmap', 'addr', 'len'],
        ['truncate', 'path', 'length'],
        ['ftruncate', 'fd', 'length'],
        ['fchmod', 'fd', 'mode'],
        ['fchown16', 'fd', 'user', 'group'],
        ['getpriority', 'which', 'who'],
        ['setpriority', 'which', 'who', 'niceval'],
        ['not implemented'],
        ['statfs', 'path', 'buf'],
        ['fstatfs', 'fd', 'buf'],
        ['ioperm', 'from', 'num', 'turn_on'],
        ['socketcall', 'call', 'args'],
        ['syslog', 'type', 'buf', 'len'],
        ['setitimer', 'which', 'value', 'ovalue'],
        ['getitimer', 'which', 'value'],
        ['newstat', 'filename', 'statbuf'],
        ['newlstat', 'filename', 'statbuf'],
        ['newfstat', 'fd', 'statbuf'],
        ['uname', '__user'],
        ['iopl', 'level', 'regs'],
        ['vhangup'],
        ['not implemented'],
        ['vm86old', '__user', 'pt_regs'],
        ['wait4', 'pid', 'stat_addr', 'options', 'ru'],
        ['swapoff', 'specialfile'],
        ['sysinfo', 'info'],
        ['ipc'],
        ['fsync', 'fd'],
        ['sigreturn', 'regs'],
        ['clone', 'clone_flags', 'newsp', 'parent_tid', 'newtls', 'child_tid'],
        ['setdomainname', 'name', 'len'],
        ['newuname', 'name'],
        ['modify_ldt', 'func', 'ptr', 'bytecount'],
        ['adjtimex', 'txc_p'],
        ['mprotect', 'start', 'len', 'prot'],
        ['sigprocmask', 'how', 'set', 'oset'],
        ['not implemented'],
        ['init_module', 'umod', 'len', 'uargs'],
        ['delete_module', 'name_user', 'flags'],
        ['not implemented'],
        ['quotactl', 'cmd', 'special', 'id', 'addr'],
        ['getpgid', 'pid'],
        ['fchdir', 'fd'],
        ['bdflush', 'func', 'data'],
        ['sysfs', 'option', 'arg1', 'arg2'],
        ['personality', 'personality'],
        ['not implemented'],
        ['setfsuid16', 'uid'],
        ['setfsgid16', 'gid'],
        ['llseek', 'fd', 'offset_high', 'offset_low', 'result', 'origin'],
        ['getdents', 'fd', 'dirent', 'count'],
        ['select', 'n', 'inp', 'outp', 'exp', 'tvp'],
        ['flock', 'fd', 'cmd'],
        ['msync', 'start', 'len', 'flags'],
        ['readv', 'fd', 'vec', 'vlen'],
        ['writev', 'fd', 'vec', 'vlen'],
        ['getsid', 'pid'],
        ['fdatasync', 'fd'],
        ['sysctl', 'args'],
        ['mlock', 'start', 'len'],
        ['munlock', 'start', 'len'],
        ['mlockall', 'flags'],
        ['munlockall'],
        ['sched_setparam', 'pid', 'param'],
        ['sched_getparam', 'pid', 'param'],
        ['sched_setscheduler', 'pid', 'policy', 'param'],
        ['sched_getscheduler', 'pid'],
        ['sched_yield'],
        ['sched_get_priority_max', 'policy'],
        ['sched_get_priority_min', 'policy'],
        ['sched_rr_get_interval', 'pid', 'interval'],
        ['nanosleep', 'rqtp', 'rmtp'],
        ['mremap', 'addr', 'old_len', 'new_len', 'flags', 'new_addr'],
        ['setresuid16', 'ruid', 'euid', 'suid'],
        ['getresuid16', 'ruid', 'euid', 'suid'],
        ['vm86', 'info', 'tsk'],
        ['not implemented'],
        ['poll', 'ufds', 'nfds', 'timeout'],
        ['nfsservctl', 'cmd', 'arg', 'res'],
        ['setresgid16', 'rgid', 'egid', 'sgid'],
        ['getresgid16', 'rgid', 'egid', 'sgid'],
        ['prctl', 'option', 'arg2', 'arg3', 'arg4', 'arg5'],
        ['rt_sigreturn', 'pt_regs'],
        ['rt_sigaction', 'sig', 'act', 'oact', 'sigsetsize'],
        ['rt_sigprocmask', 'how', 'set', 'oset', 'sigsetsize'],
        ['rt_sigpending', 'set', 'sigsetsize'],
        ['rt_sigtimedwait', 'uthese', 'uinfo', 'uts', 'sigsetsize'],
        ['rt_sigqueueinfo', 'pid', 'sig', 'uinfo'],
        ['rt_sigsuspend', 'unewset', 'sigsetsize'],
        ['pread64', 'fd', 'buf', 'count', 'pos'],
        ['pwrite64', 'fd', 'buf', 'count', 'pos'],
        ['chown16', 'filename', 'user', 'group'],
        ['getcwd', 'buf', 'size'],
        ['capget', 'header', 'dataptr'],
        ['capset', 'header', 'data'],
        ['sigaltstack', '__user', '__user', 'pt_regs'],
        ['sendfile', 'out_fd', 'in_fd', 'offset', 'count'],
        ['not implemented'],
        ['not implemented'],
        ['vfork', 'pt_regs'],
        ['getrlimit', 'resource', 'rlim'],
        ['mmap_pgoff'],
        ['truncate64', 'path', 'length'],
        ['ftruncate64', 'fd', 'length'],
        ['stat64', 'filename', 'statbuf'],
        ['lstat64', 'filename', 'statbuf'],
        ['fstat64', 'fd', 'statbuf'],
        ['lchown', 'filename', 'user', 'group'],
        ['getuid'],
        ['getgid'],
        ['geteuid'],
        ['getegid'],
        ['setreuid', 'ruid', 'euid'],
        ['setregid', 'rgid', 'egid'],
        ['getgroups', 'gidsetsize', 'grouplist'],
        ['setgroups', 'gidsetsize', 'grouplist'],
        ['fchown', 'fd', 'user', 'group'],
        ['setresuid', 'ruid', 'euid', 'suid'],
        ['getresuid', 'ruid', 'euid', 'suid'],
        ['setresgid', 'rgid', 'egid', 'sgid'],
        ['getresgid', 'rgid', 'egid', 'sgid'],
        ['chown', 'filename', 'user', 'group'],
        ['setuid', 'uid'],
        ['setgid', 'gid'],
        ['setfsuid', 'uid'],
        ['setfsgid', 'gid'],
        ['pivot_root', 'new_root', 'put_old'],
        ['mincore', 'start', 'len', 'vec'],
        ['madvise', 'start', 'len', 'behavior'],
        ['getdents64', 'fd', 'dirent', 'count'],
        ['fcntl64', 'fd', 'cmd', 'arg'],
        ['not implemented'],
        ['not implemented'],
        ['gettid'],
        ['readahead', 'fd', 'offset', 'count'],
        ['setxattr', 'path', 'name', 'value', 'size', 'flags'],
        ['lsetxattr', 'path', 'name', 'value', 'size', 'flags'],
        ['fsetxattr', 'fd', 'name', 'value', 'size', 'flags'],
        ['getxattr', 'path', 'name', 'value', 'size'],
        ['lgetxattr', 'path', 'name', 'value', 'size'],
        ['fgetxattr', 'fd', 'name', 'value', 'size'],
        ['listxattr', 'path', 'list', 'size'],
        ['llistxattr', 'path', 'list', 'size'],
        ['flistxattr', 'fd', 'list', 'size'],
        ['removexattr', 'path', 'name'],
        ['lremovexattr', 'path', 'name'],
        ['fremovexattr', 'fd', 'name'],
        ['tkill', 'pid', 'sig'],
        ['sendfile64', 'out_fd', 'in_fd', 'offset', 'count'],
        ['futex'],
        ['sched_setaffinity', 'pid', 'len', 'user_mask_ptr'],
        ['sched_getaffinity', 'pid', 'len', 'user_mask_ptr'],
        ['set_thread_area', '__user'],
        ['get_thread_area', '__user'],
        ['io_setup', 'nr_reqs', 'ctx'],
        ['io_destroy', 'ctx'],
        ['io_getevents', 'ctx_id', 'min_nr', 'nr', 'events', 'timeout'],
        ['io_submit', 'ctx_id', 'nr', 'iocbpp'],
        ['io_cancel', 'ctx_id', 'iocb', 'result'],
        ['fadvise64', 'fd', 'offset', 'len', 'advice'],
        ['not implemented'],
        ['exit_group', 'error_code'],
        ['lookup_dcookie', 'cookie64', 'buf', 'len'],
        ['epoll_create', 'size'],
        ['epoll_ctl', 'epfd', 'op', 'fd', 'event'],
        ['epoll_wait', 'epfd', 'events', 'maxevents', 'timeout'],
        ['remap_file_pages', 'start', 'size', 'prot', 'pgoff', 'flags'],
        ['set_tid_address', 'tidptr'],
        ['timer_create', 'which_clock', 'timer_event_spec', 'created_timer_id'],
        ['timer_settime', 'timer_id', 'flags', 'new_setting', 'old_setting'],
        ['timer_gettime', 'timer_id', 'setting'],
        ['timer_getoverrun', 'timer_id'],
        ['timer_delete', 'timer_id'],
        ['clock_settime', 'which_clock', 'tp'],
        ['clock_gettime', 'which_clock', 'tp'],
        ['clock_getres', 'which_clock', 'tp'],
        ['clock_nanosleep', 'which_clock', 'flags', 'rqtp', 'rmtp'],
        ['statfs64', 'path', 'sz', 'buf'],
        ['fstatfs64', 'fd', 'sz', 'buf'],
        ['tgkill', 'tgid', 'pid', 'sig'],
        ['utimes', 'filename', 'utimes'],
        ['fadvise64_64', 'fd', 'offset', 'len', 'advice'],
        ['not implemented'],
        ['mbind'],
        ['get_mempolicy', 'policy', 'nmask', 'maxnode', 'addr', 'flags'],
        ['set_mempolicy', 'mode', 'nmask', 'maxnode'],
        ['mq_open', 'name', 'oflag', 'mode', 'attr'],
        ['mq_unlink', 'name'],
        ['mq_timedsend', 'mqdes', 'msg_ptr', 'msg_len', 'msg_prio', 'abs_timeout'],
        ['mq_timedreceive', 'mqdes', 'msg_ptr', 'msg_len', 'msg_prio', 'abs_timeout'],
        ['mq_notify', 'mqdes', 'notification'],
        ['mq_getsetattr', 'mqdes', 'mqstat', 'omqstat'],
        ['kexec_load', 'entry', 'nr_segments', 'segments', 'flags'],
        ['waitid', 'which', 'pid', 'infop', 'options', 'ru'],
        ['not implemented'],
        ['add_key', '_type', '_description', '_payload', 'plen', 'destringid'],
        ['request_key', '_type', '_description', '_callout_info', 'destringid'],
        ['keyctl', 'cmd', 'arg2', 'arg3', 'arg4', 'arg5'],
        ['ioprio_set', 'which', 'who', 'ioprio'],
        ['ioprio_get', 'which', 'who'],
        ['inotify_init'],
        ['inotify_add_watch', 'fd', 'path', 'mask'],
        ['inotify_rm_watch', 'fd', 'wd'],
        ['migrate_pages', 'pid', 'maxnode', 'from', 'to'],
        ['openat', 'dfd', 'filename', 'flags', 'mode'],
        ['mkdirat', 'dfd', 'pathname', 'mode'],
        ['mknodat', 'dfd', 'filename', 'mode', 'dev'],
        ['fchownat', 'dfd', 'filename', 'user', 'group', 'flag'],
        ['futimesat', 'dfd', 'filename', 'utimes'],
        ['fstatat64', 'dfd', 'filename', 'statbuf', 'flag'],
        ['unlinkat', 'dfd', 'pathname', 'flag'],
        ['renameat', 'olddfd', 'oldname', 'newdfd', 'newname'],
        ['linkat', 'olddfd', 'oldname', 'newdfd', 'newname', 'flags'],
        ['symlinkat', 'oldname', 'newdfd', 'newname'],
        ['readlinkat', 'dfd', 'path', 'buf', 'bufsiz'],
        ['fchmodat', 'dfd', 'filename', 'mode'],
        ['faccessat', 'dfd', 'filename', 'mode'],
        ['pselect6'],
        ['ppoll', 'ufds', 'nfds', 'tsp', 'sigmask', 'sigsetsize'],
        ['unshare', 'unshare_flags'],
        ['set_robust_list', 'head', 'len'],
        ['get_robust_list', 'pid', 'head_ptr', 'len_ptr'],
        ['splice'],
        ['sync_file_range', 'fd', 'offset', 'nbytes', 'flags'],
        ['tee', 'fdin', 'fdout', 'len', 'flags'],
        ['vmsplice', 'fd', 'iov', 'nr_segs', 'flags'],
        ['move_pages'],
        ['getcpu', 'cpu', 'node', 'cache'],
        ['epoll_pwait'],
        ['utimensat', 'dfd', 'filename', 'utimes', 'flags'],
        ['signalfd', 'ufd', 'user_mask', 'sizemask'],
        ['timerfd_create', 'clockid', 'flags'],
        ['eventfd', 'count'],
        ['fallocate', 'fd', 'mode', 'offset', 'len'],
        ['timerfd_settime', 'ufd', 'flags', 'utmr', 'otmr'],
        ['timerfd_gettime', 'ufd', 'otmr'],
        ['signalfd4', 'ufd', 'user_mask', 'sizemask', 'flags'],
        ['eventfd2', 'count', 'flags'],
        ['epoll_create1', 'flags'],
        ['dup3', 'oldfd', 'newfd', 'flags'],
        ['pipe2', 'fildes', 'flags'],
        ['inotify_init1', 'flags'],
        ['preadv', 'fd', 'vec', 'vlen', 'pos_l', 'pos_h'],
        ['pwritev', 'fd', 'vec', 'vlen', 'pos_l', 'pos_h'],
        ['rt_tgsigqueueinfo', 'tgid', 'pid', 'sig', 'uinfo'],
        ['perf_event_open', 'attr_uptr', 'pid', 'cpu', 'group_fd', 'flags'],
        ['recvmmsg', 'fd', 'msg', 'vlen', 'flags', 'timeout'],
    ],
    "x86_64": [
        ['read', 'fd', 'buf', 'count'],
        ['write', 'fd', 'buf', 'count'],
        ['open', 'filename', 'flags', 'mode'],
        ['close', 'fd'],
        ['stat', 'filename', 'statbuf'],
        ['fstat', 'fd', 'statbuf'],
        ['lstat', 'filename', 'statbuf'],
        ['poll', 'ufds', 'nfds', 'timeout_msecs'],
        ['lseek', 'fd', 'offset', 'origin'],
        ['mmap', 'addr', 'len', 'prot', 'flags', 'fd', 'off'],
        ['mprotect', 'start', 'len', 'prot'],
        ['munmap', 'addr', 'len'],
        ['brk', 'brk'],
        ['rt_sigaction', 'sig', 'act', 'oact', 'sigsetsize'],
        ['rt_sigprocmask', 'how', 'nset', 'oset', 'sigsetsize'],
        ['rt_sigreturn', '__unused'],
        ['ioctl', 'fd', 'cmd', 'arg'],
        ['pread64', 'fd', 'buf', 'count', 'pos'],
        ['pwrite64', 'fd', 'buf', 'count', 'pos'],
        ['readv', 'fd', 'vec', 'vlen'],
        ['writev', 'fd', 'vec', 'vlen'],
        ['access', 'filename', 'mode'],
        ['pipe', 'filedes'],
        ['select', 'n', 'inp', 'outp', 'fd_set*exp', 'tvp'],
        ['sched_yield'],
        ['mremap', 'addr', 'old_len', 'new_len', 'flags', 'new_addr'],
        ['msync', 'start', 'len', 'flags'],
        ['mincore', 'start', 'len', 'vec'],
        ['madvise', 'start', 'len_in', 'behavior'],
        ['shmget', 'key', 'size', 'shmflg'],
        ['shmat', 'shmid', 'shmaddr', 'shmflg'],
        ['shmctl', 'shmid', 'cmd', 'buf'],
        ['dup', 'fildes'],
        ['dup2', 'oldfd', 'newfd'],
        ['pause'],
        ['nanosleep', 'rqtp', 'rmtp'],
        ['getitimer', 'which', 'value'],
        ['alarm', 'seconds'],
        ['setitimer', 'which', 'value', 'ovalue'],
        ['getpid'],
        ['sendfile', 'out_fd', 'in_fd', 'offset', 'count'],
        ['socket', 'family', 'type', 'protocol'],
        ['connect', 'fd', 'uservaddr', 'addrlen'],
        ['accept', 'fd', 'upeer_sockaddr', 'upeer_addrlen'],
        ['sendto', 'fd', 'buff', 'len', 'flags', 'addr', 'addr_len'],
        ['recvfrom', 'fd', 'ubuf', 'size', 'flags', 'addr', 'addr_len'],
        ['sendmsg', 'fd', 'msg', 'flags'],
        ['recvmsg', 'fd', 'msg', 'flags'],
        ['shutdown', 'fd', 'how'],
        ['bind', 'fd', 'umyaddr', 'addrlen'],
        ['listen', 'fd', 'backlog'],
        ['getsockname', 'fd', 'usockaddr', 'usockaddr_len'],
        ['getpeername', 'fd', 'usockaddr', 'usockaddr_len'],
        ['socketpair', 'family', 'type', 'protocol', 'usockvec'],
        ['setsockopt', 'fd', 'level', 'optname', 'optval', 'optlen'],
        ['getsockopt', 'fd', 'level', 'optname', 'optval', 'optlen'],
        ['clone', 'clone_flags', 'newsp', 'parent_tid', 'child_tid'],
        ['fork'],
        ['vfork'],
        ['execve', 'filename', 'argv[]', 'envp[]'],
        ['exit', 'error_code'],
        ['wait4', 'upid', 'stat_addr', 'options', 'ru'],
        ['kill', 'pid', 'sig'],
        ['uname', 'name'],
        ['semget', 'key', 'nsems', 'semflg'],
        ['semop', 'semid', 'tsops', 'nsops'],
        ['semctl', 'semid', 'semnum', 'cmd', 'arg'],
        ['shmdt', 'shmaddr'],
        ['msgget', 'key', 'msgflg'],
        ['msgsnd', 'msqid', 'msgp', 'msgsz', 'msgflg'],
        ['msgrcv', 'msqid', 'msgp', 'msgsz', 'msgtyp', 'msgflg'],
        ['msgctl', 'msqid', 'cmd', 'buf'],
        ['fcntl', 'fd', 'cmd', 'arg'],
        ['flock', 'fd', 'cmd'],
        ['fsync', 'fd'],
        ['fdatasync', 'fd'],
        ['truncate', 'path', 'length'],
        ['ftruncate', 'fd', 'length'],
        ['getdents', 'fd', 'dirent', 'count'],
        ['getcwd', 'buf', 'size'],
        ['chdir', 'filename'],
        ['fchdir', 'fd'],
        ['rename', 'oldname', 'newname'],
        ['mkdir', 'pathname', 'mode'],
        ['rmdir', 'pathname'],
        ['creat', 'pathname', 'mode'],
        ['link', 'oldname', 'newname'],
        ['unlink', 'pathname'],
        ['symlink', 'oldname', 'newname'],
        ['readlink', 'path', 'buf', 'bufsiz'],
        ['chmod', 'filename', 'mode'],
        ['fchmod', 'fd', 'mode'],
        ['chown', 'filename', 'user', 'group'],
        ['fchown', 'fd', 'user', 'group'],
        ['lchown', 'filename', 'user', 'group'],
        ['umask', 'mask'],
        ['gettimeofday', 'tv', 'tz'],
        ['getrlimit', 'resource', 'rlim'],
        ['getrusage', 'who', 'ru'],
        ['sysinfo', 'info'],
        ['times', 'info'],
        ['ptrace', 'request', 'pid', 'addr', 'data'],
        ['getuid'],
        ['syslog', 'type', 'buf', 'len'],
        ['getgid'],
        ['setuid', 'uid'],
        ['setgid', 'gid'],
        ['geteuid'],
        ['getegid'],
        ['setpgid', 'pid', 'pgid'],
        ['getppid'],
        ['getpgrp'],
        ['setsid'],
        ['setreuid', 'ruid', 'euid'],
        ['setregid', 'rgid', 'egid'],
        ['getgroups', 'gidsetsize', 'grouplist'],
        ['setgroups', 'gidsetsize', 'grouplist'],
        ['setresuid', 'ruid', 'euid', 'suid'],
        ['getresuid', 'ruid', 'euid', 'suid'],
        ['setresgid', 'rgid', 'egid', 'sgid'],
        ['getresgid', 'rgid', 'egid', 'sgid'],
        ['getpgid', 'pid'],
        ['setfsuid', 'uid'],
        ['setfsgid', 'gid'],
        ['getsid', 'pid'],
        ['capget', 'header', 'dataptr'],
        ['capset', 'header', 'data'],
        ['rt_sigpending', 'set', 'sigsetsize'],
        ['rt_sigtimedwait', 'uthese', 'uinfo', 'uts', 'sigsetsize'],
        ['rt_sigqueueinfo', 'pid', 'sig', 'uinfo'],
        ['rt_sigsuspend', 'unewset', 'sigsetsize'],
        ['sigaltstack', 'uss', 'uoss'],
        ['utime', 'filename', 'times'],
        ['mknod', 'filename', 'mode', 'dev'],
        ['not implemented'],
        ['personality', 'personality'],
        ['ustat', 'dev', 'ubuf'],
        ['statfs', 'pathname', 'buf'],
        ['fstatfs', 'fd', 'buf'],
        ['sysfs', 'option', 'arg1', 'arg2'],
        ['getpriority', 'which', 'who'],
        ['setpriority', 'which', 'who', 'niceval'],
        ['sched_setparam', 'pid', 'param'],
        ['sched_getparam', 'pid', 'param'],
        ['sched_setscheduler', 'pid', 'policy', 'param'],
        ['sched_getscheduler', 'pid'],
        ['sched_get_priority_max', 'policy'],
        ['sched_get_priority_min', 'policy'],
        ['sched_rr_get_interval', 'pid', 'interval'],
        ['mlock', 'start', 'len'],
        ['munlock', 'start', 'len'],
        ['mlockall', 'flags'],
        ['munlockall'],
        ['vhangup'],
        ['modify_ldt', 'func', 'ptr', 'bytecount'],
        ['pivot_root', 'new_root', 'put_old'],
        ['_sysctl', 'args'],
        ['prctl', 'option', 'arg2', 'arg3', 'arg4', 'arg5'],
        ['arch_prctl', 'task', 'code', 'addr'],
        ['adjtimex', 'txc_p'],
        ['setrlimit', 'resource', 'rlim'],
        ['chroot', 'filename'],
        ['sync'],
        ['acct', 'name'],
        ['settimeofday', 'tv', 'tz'],
        ['mount', 'dev_name', 'dir_name', 'type', 'flags', 'data'],
        ['umount2', 'target', 'flags'],
        ['swapon', 'specialfile', 'swap_flags'],
        ['swapoff', 'specialfile'],
        ['reboot', 'magic1', 'magic2', 'cmd', 'arg'],
        ['sethostname', 'name', 'len'],
        ['setdomainname', 'name', 'len'],
        ['iopl', 'level', 'regs'],
        ['ioperm', 'from', 'num', 'turn_on'],
        ['create_module', '2.6'],
        ['init_module', 'umod', 'len', 'uargs'],
        ['delete_module', 'name_user', 'flags'],
        ['get_kernel_syms', '2.6'],
        ['query_module', '2.6'],
        ['quotactl', 'cmd', 'special', 'id', 'addr'],
        ['not implemented'],
        ['not implemented'],
        ['not implemented'],
        ['not implemented'],
        ['not implemented'],
        ['not implemented'],
        ['gettid'],
        ['readahead', 'fd', 'offset', 'count'],
        ['setxattr', 'pathname', 'name', 'value', 'size', 'flags'],
        ['lsetxattr', 'pathname', 'name', 'value', 'size', 'flags'],
        ['fsetxattr', 'fd', 'name', 'value', 'size', 'flags'],
        ['getxattr', 'pathname', 'name', 'value', 'size'],
        ['lgetxattr', 'pathname', 'name', 'value', 'size'],
        ['fgetxattr', 'fd', 'name', 'value', 'size'],
        ['listxattr', 'pathname', 'list', 'size'],
        ['llistxattr', 'pathname', 'list', 'size'],
        ['flistxattr', 'fd', 'list', 'size'],
        ['removexattr', 'pathname', 'name'],
        ['lremovexattr', 'pathname', 'name'],
        ['fremovexattr', 'fd', 'name'],
        ['tkill', 'pid', 'sig'],
        ['time', 'tloc'],
        ['futex', 'uaddr', 'op', 'val', 'utime', 'uaddr2', 'val3'],
        ['sched_setaffinity', 'pid', 'len', 'user_mask_ptr'],
        ['sched_getaffinity', 'pid', 'len', 'user_mask_ptr'],
        ['set_thread_area', 'arch_prctl'],
        ['io_setup', 'nr_events', 'ctxp'],
        ['io_destroy', 'ctx'],
        ['io_getevents', 'ctx_id', 'min_nr', 'nr', 'events'],
        ['io_submit', 'ctx_id', 'nr', '*iocbpp'],
        ['io_cancel', 'ctx_id', 'iocb', 'result'],
        ['get_thread_area', 'arch_prctl'],
        ['lookup_dcookie', 'cookie64', 'buf', 'len'],
        ['epoll_create', 'size'],
        ['not implemented'],
        ['not implemented'],
        ['remap_file_pages', 'start', 'size', 'prot', 'pgoff', 'flags'],
        ['getdents64', 'fd', 'dirent', 'count'],
        ['set_tid_address', 'tidptr'],
        ['restart_syscall'],
        ['semtimedop', 'semid', 'tsops', 'nsops', 'timeout'],
        ['fadvise64', 'fd', 'offset', 'len', 'advice'],
        ['timer_create', 'which_clock', 'timer_event_spec', 'created_timer_id'],
        ['timer_settime', 'timer_id', 'flags', 'new_setting', 'old_setting'],
        ['timer_gettime', 'timer_id', 'setting'],
        ['timer_getoverrun', 'timer_id'],
        ['timer_delete', 'timer_id'],
        ['clock_settime', 'which_clock', 'tp'],
        ['clock_gettime', 'which_clock', 'tp'],
        ['clock_getres', 'which_clock', 'tp'],
        ['clock_nanosleep', 'which_clock', 'flags', 'rqtp', 'rmtp'],
        ['exit_group', 'error_code'],
        ['epoll_wait', 'epfd', 'events', 'maxevents', 'timeout'],
        ['epoll_ctl', 'epfd', 'op', 'fd', 'event'],
        ['tgkill', 'tgid', 'pid', 'sig'],
        ['utimes', 'filename', 'utimes'],
        ['not implemented'],
        ['mbind', 'start', 'len', 'mode', 'nmask', 'maxnode', 'flags'],
        ['set_mempolicy', 'mode', 'nmask', 'maxnode'],
        ['get_mempolicy', 'policy', 'nmask', 'maxnode', 'addr', 'flags'],
        ['mq_open', 'u_name', 'oflag', 'mode', 'u_attr'],
        ['mq_unlink', 'u_name'],
        ['mq_timedsend', 'mqdes', 'u_msg_ptr', 'msg_len', 'msg_prio', 'u_abs_timeout'],
        ['mq_timedreceive', 'mqdes', 'u_msg_ptr', 'msg_len', 'u_msg_prio', 'u_abs_timeout'],
        ['mq_notify', 'mqdes', 'u_notification'],
        ['mq_getsetattr', 'mqdes', 'u_mqstat', 'u_omqstat'],
        ['kexec_load', 'entry', 'nr_segments', 'segments', 'flags'],
        ['waitid', 'which', 'upid', 'infop', 'options', 'ru'],
        ['add_key', '_type', '_description', '_payload', 'plen'],
        ['request_key', '_type', '_description', '_callout_info', 'destringid'],
        ['keyctl', 'option', 'arg2', 'arg3', 'arg4', 'arg5'],
        ['ioprio_set', 'which', 'who', 'ioprio'],
        ['ioprio_get', 'which', 'who'],
        ['inotify_init'],
        ['inotify_add_watch', 'fd', 'pathname', 'mask'],
        ['inotify_rm_watch', 'fd', 'wd'],
        ['migrate_pages', 'pid', 'maxnode', 'old_nodes', 'new_nodes'],
        ['openat', 'dfd', 'filename', 'flags', 'mode'],
        ['mkdirat', 'dfd', 'pathname', 'mode'],
        ['mknodat', 'dfd', 'filename', 'mode', 'dev'],
        ['fchownat', 'dfd', 'filename', 'user', 'group', 'flag'],
        ['futimesat', 'dfd', 'filename', 'utimes'],
        ['newfstatat', 'dfd', 'filename', 'statbuf', 'flag'],
        ['unlinkat', 'dfd', 'pathname', 'flag'],
        ['renameat', 'oldfd', 'oldname', 'newfd', 'newname'],
        ['linkat', 'oldfd', 'oldname', 'newfd', 'newname', 'flags'],
        ['symlinkat', 'oldname', 'newfd', 'newname'],
        ['readlinkat', 'dfd', 'pathname', 'buf', 'bufsiz'],
        ['fchmodat', 'dfd', 'filename', 'mode'],
        ['faccessat', 'dfd', 'filename', 'mode'],
        ['pselect6', 'n', 'inp', 'outp', 'exp', 'tsp', 'sig'],
        ['ppoll', 'ufds', 'nfds', 'tsp', 'sigmask', 'sigsetsize'],
        ['unshare', 'unshare_flags'],
        ['set_robust_list', 'head', 'len'],
        ['get_robust_list', 'pid', '*head_ptr', 'len_ptr'],
        ['splice', 'fd_in', 'off_in', 'fd_out', 'off_out', 'len', 'flags'],
        ['tee', 'fdin', 'fdout', 'len', 'flags'],
        ['sync_file_range', 'fd', 'offset', 'bytes', 'flags'],
        ['vmsplice', 'fd', 'iov', 'nr_segs', 'flags'],
        ['move_pages', 'pid', 'nr_pages', '*pages', 'nodes', 'status', 'flags'],
        ['utimensat', 'dfd', 'filename', 'utimes', 'flags'],
        ['epoll_pwait', 'epfd', 'events', 'maxevents', 'timeout', 'sigmask', 'sigsetsize'],
        ['signalfd', 'ufd', 'user_mask', 'sizemask'],
        ['timerfd_create', 'clockid', 'flags'],
        ['eventfd', 'count'],
        ['fallocate', 'fd', 'mode', 'offset', 'len'],
        ['timerfd_settime', 'ufd', 'flags', 'utmr', 'otmr'],
        ['timerfd_gettime', 'ufd', 'otmr'],
        ['accept4', 'fd', 'upeer_sockaddr', 'upeer_addrlen', 'flags'],
        ['signalfd4', 'ufd', 'user_mask', 'sizemask', 'flags'],
        ['eventfd2', 'count', 'flags'],
        ['epoll_create1', 'flags'],
        ['dup3', 'oldfd', 'newfd', 'flags'],
        ['pipe2', 'filedes', 'flags'],
        ['inotify_init1', 'flags'],
        ['preadv', 'fd', 'vec', 'vlen', 'pos_l', 'pos_h'],
        ['pwritev', 'fd', 'vec', 'vlen', 'pos_l', 'pos_h'],
        ['rt_tgsigqueueinfo', 'tgid', 'pid', 'sig', 'uinfo'],
        ['perf_event_open', 'attr_uptr', 'pid', 'cpu', 'group_fd', 'flags'],
        ['recvmmsg', 'fd', 'mmsg', 'vlen', 'flags', 'timeout'],
        ['fanotify_init', 'flags', 'event_f_flags'],
        ['fanotify_mark', 'fanotify_fd', 'flags', 'mask', 'dfd', 'pathname'],
        ['prlimit64', 'pid', 'resource', 'new_rlim', 'old_rlim'],
        ['name_to_handle_at', 'dfd', 'name', 'handle', 'mnt_id', 'flag'],
        ['open_by_handle_at', 'dfd', 'name', 'handle', 'mnt_id', 'flags'],
        ['clock_adjtime', 'which_clock', 'tx'],
        ['syncfs', 'fd'],
        ['sendmmsg', 'fd', 'mmsg', 'vlen', 'flags'],
        ['setns', 'fd', 'nstype'],
        ['getcpu', 'cpup', 'nodep', 'unused'],
        ['process_vm_readv', 'pid', 'lvec', 'liovcnt', 'rvec', 'riovcnt', 'flags'],
        ['process_vm_writev', 'pid', 'lvec', 'liovcnt', 'rvec', 'riovcnt', 'flags'],
    ]
}
